# 基础配置
title: 草均约拍工作室
description: >-
  杭州自然光人像摄影 | 情侣写真定制 | 毕业季跟拍
url: "https://caojun.studio" # 绑定自定义域名后修改
repository: yourname/yourname.github.io # 替换为你的仓库名

# 主题配置
theme: minimal-mistakes
remote_theme: mmistakes/minimal-mistakes@4.24.0 # 锁定主题版本

# 插件配置
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# 网站结构
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

# 导航栏配置
navigation:
  main:
    - title: "作品集"
      url: /portfolio/
    - title: "服务报价"
      url: /pricing/
    - title: "预约拍摄"
      url: /booking/
    - title: "关于我们"
      url: /about/

# 优化参数
seo:
  type: Organization
  links:
    - "https://weibo.com/yourpage"
    - "https://www.xiaohongshu.com/user/yourpage"